version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-image-label"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a44qnx1odbgt"
s3_prefix = "aws-lambda-image-label"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=488113704612.dkr.ecr.us-east-1.amazonaws.com/helloworldrepo"]
